apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qa
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
      - persistentvolumes
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
